### ISSUE TITLE
Getting error when running the same project. Calling method 'start_suite' of listener 

### ISSUE THREAD

**Issue by Srihari88** [adiralashiva8/robotframework-ares#1]
FirstSuite                                                                    
==============================================================================
[ ERROR ] Calling method 'start_suite' of listener '/Users/reenupanwar/PycharmProjects/robotframework-ares-master/Tests/AresListener.py' failed: KeyError: 'data'
[ ERROR ] Calling method 'start_test' of listener '/Users/reenupanwar/PycharmProjects/robotframework-ares-master/Tests/AresListener.py' failed: AttributeError: 'AresListener' object has no attribute 'test_count'
[ ERROR ] Calling method 'end_test' of listener '/Users/reenupanwar/PycharmProjects/robotframework-ares-master/Tests/AresListener.py' failed: AttributeError: 'AresListener' object has no attribute 'test_count'
Test Case 1                                                           | FAIL |
Robot != framework
------------------------------------------------------------------------------
[ ERROR ] Calling method 'start_test' of listener '/Users/reenupanwar/PycharmProjects/robotframework-ares-master/Tests/AresListener.py' failed: AttributeError: 'AresListener' object has no attribute 'test_count'
[ ERROR ] Calling method 'end_test' of listener '/Users/reenupanwar/PycharmProjects/robotframework-ares-master/Tests/AresListener.py' failed: AttributeError: 'AresListener' object has no attribute 'test_count'
Test Case 2                                                           | PASS |
------------------------------------------------------------------------------
[ ERROR ] Calling method 'start_test' of listener '/Users/reenupanwar/PycharmProjects/robotframework-ares-master/Tests/AresListener.py' failed: AttributeError: 'AresListener' object has no attribute 'test_count'
[ ERROR ] Calling method 'end_test' of listener '/Users/reenupanwar/PycharmProjects/robotframework-ares-master/Tests/AresListener.py' failed: AttributeError: 'AresListener' object has no attribute 'test_count'
Test Case 3                                                           | FAIL |
'1>2' should be true.
------------------------------------------------------------------------------
[ ERROR ] Calling method 'end_suite' of listener '/Users/reenupanwar/PycharmProjects/robotframework-ares-master/Tests/AresListener.py' failed: AttributeError: 'AresListener' object has no attribute 'test_count'
FirstSuite                                                            | FAIL |
3 critical tests, 1 passed, 2 failed
3 tests total, 1 passed, 2 failed
==============================================================================
Output:  /Users/reenupanwar/PycharmProjects/robotframework-ares-master/Tests/output.xml
Log:     /Users/reenupanwar/PycharmProjects/robotframework-ares-master/Tests/log.html
Report:  /Users/reenupanwar/PycharmProjects/robotframework-ares-master/Tests/report.html
[ ERROR ] Calling method 'close' of listener '/Users/reenupanwar/PycharmProjects/robotframework-ares-master/Tests/AresListener.py' failed: KeyError: 'data'

**Comment by adiralashiva8** [comment]
Could you please provide your robotframework version. In think this is issue with robotframework listener version

**Comment by adiralashiva8** [comment]
And also please provide the run command used. Currently pabot is not supported for this listener

**Comment by Srihari88** [comment]
Here is the RobotFramework version.

Name: robotframework
Version: 3.1.1
Summary: Generic automation framework for acceptance testing and robotic
process automation (RPA)
Home-page: http://robotframework.org
Author: Pekka Klärck
Author-email: peke@eliga.fi


Thanks & Regards
P.SriHariNaidu

**Comment by Srihari88** [comment]
robot --listener AresListener.py -V config.py FirstSuite.robot

Thanks & Regards
P.SriHariNaidu

**Comment by adiralashiva8** [comment]
My guess is ROBOT_LISTENER_API_VERSION got changed. It should be 3
As per error message it say's KeyError 'data' which got introduced in listener version 3
Reference - http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-version-3

**Comment by elyess78** [comment]
i have the same problem with the same version of robot 3.1.1

**Comment by adiralashiva8** [comment]
@elyess78 Is it mac or windows

**Comment by elyess78** [comment]
@adiralashiva8  Windows10. what about you, you use the version 3.1.1 for robot?

**Comment by adiralashiva8** [comment]
Yes, Robot Framework 3.1.1 (Python 2.7.14 on win32)

**Comment by elyess78** [comment]
for python i use version 2.7.10 win64

**Comment by adiralashiva8** [comment]
Does it causing issue

**Comment by CapDam** [comment]
I have the same problem with mac os and robot framework 3.1.1

**Comment by Srihari88** [comment]
The request got failed & there is no console message/information to indicate the exact issue. I would like to suggest display the status message. 

The issue occurs due to incorrect workspace name on the config.py file. This is working fine now.
